### ISSUE TITLE
Add SQL UPDATE Statement

### ISSUE THREAD

**Issue by NateLevin1** [UltimatePro-Grammer/JSQL#11]
This is an important statement that should be implemented before 1.0.0.

Syntax is
```sql
UPDATE (multi_ident)
SET colName = (expression), col2Name = (expression)
[WHERE (predicate)]
```
Note that `SET` is not optional in the statement.

Additionally, the note in #10 also applies here.

**Comment by UltimatePro-Grammer** [comment]
[`Collection.modify()`](https://dexie.org/docs/Collection/Collection.modify()) is the Dexie function we should use here.

**Comment by UltimatePro-Grammer** [comment]
Added in c18b4bba1ffb5934712d9ffc203c5424dde80644, documented in 9d2cd622dd46e23aa46bc7f17b503dabe0697d2b.
